# Generated by Django 5.1.2 on 2026-07-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.IntegerField(default=1000)),
                ('sold_price', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='auction/')),
            ],
        ),
        migrations.CreateModel(
            name='GallerySeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('result', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('President', 'President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], max_length=50)),
                ('image', models.ImageField(upload_to='members/')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='notices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('phone', models.CharField(default='', max_length=15)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket Keeper', 'Wicket Keeper')], default='Batsman', max_length=50)),
                ('address', models.TextField(default='')),
                ('photo', models.ImageField(default='default.jpg', upload_to='players/')),
                ('payment_screenshot', models.ImageField(default='default.jpg', upload_to='payments/')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('age_category', models.CharField(choices=[('Under 20', 'Under 20'), ('Above 20', 'Above 20')], default='Under 20', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='registrations/')),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='aadhar/')),
                ('payment_screenshot', models.ImageField(upload_to='payments/')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=100)),
                ('man_of_the_match', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('overs', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sponsors/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(default='default.jpg', upload_to='teams/')),
                ('captain', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.galleryseason')),
            ],
        ),
    ]
