# Generated by Django 5.1.2 on 2026-05-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_time',
            new_name='time',
        ),
    ]
