# Generated by Django 5.1.2 on 2026-07-18 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot',
            field=models.FileField(upload_to='payments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(upload_to='registrations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
