# Generated by Django 5.1.2 on 2026-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_sponsor_trophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_logo', models.ImageField(upload_to='live_score/')),
                ('team2_logo', models.ImageField(upload_to='live_score/')),
                ('score', models.CharField(max_length=100)),
                ('wickets', models.CharField(max_length=20)),
                ('overs', models.CharField(max_length=20)),
                ('current_run_rate', models.CharField(max_length=20)),
                ('batsman1', models.CharField(max_length=100)),
                ('batsman1_score', models.CharField(max_length=20)),
                ('batsman2', models.CharField(max_length=100)),
                ('batsman2_score', models.CharField(max_length=20)),
                ('bowler', models.CharField(max_length=100)),
                ('bowler_figures', models.CharField(max_length=50)),
                ('toss', models.CharField(max_length=200)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
