# Generated by Django 5.1.2 on 2026-05-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_livematch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveMatch',
        ),
    ]
