# Generated by Django 5.1.2 on 2026-05-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_trophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.IntegerField(default=1000)),
                ('sold_price', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='auction/')),
            ],
        ),
    ]
