# Generated by Django 5.1.2 on 2026-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar/'),
        ),
    ]
