# Generated by Django 5.1.2 on 2026-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_galleryimage_galleryseason_delete_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryseason',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='season_cover/'),
        ),
    ]
