# Generated by Django 5.1.2 on 2026-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_galleryseason_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryseason',
            name='cover_image',
        ),
    ]
